environment:
  matrix:
    - TARGET: x86_64-pc-windows-msvc

build: false

install:
  - ps: Start-FileDownload "https://static.rust-lang.org/dist/rust-nightly-${env:TARGET}.exe"
  - rust-nightly-%TARGET%.exe /VERYSILENT /NORESTART /DIR="C:\Program Files\Rust"
  - SET PATH=%PATH%;C:\Program Files\Rust\bin
  - rustc -V
  - cargo -V

test_script:
    - cargo test --verbose

artifacts:
    - path: ./target/