[package]
name = "bruteforce"
version = "0.1.0"
authors = ["Boris Pfahringer <bpnzltd@gmail.com>"]

[dependencies]
libc = "0.2"
petgraph = "*"

[dependencies.bindgen]
git = "https://github.com/crabtw/rust-bindgen.git"

[build-dependencies]
gcc = "0.3"
